version: "3.3"

services: 
  
  db:
  image: jusk2/postgres:13
  environment:
    - POSTGRES_DB=mobiusdb
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=dksdlfduq2
    - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  volumes:
    - ./init/:/docker-entrypoint-initdb.d/
  ports:
    - 5432:5432

  mobius:
    image: jusk2/onem2m-mobius
    ports:
      - 7579:7579
    restart: always
    link:
      - db
    depends_on:
      - db

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    depends_on:
      - db

  rosemary:
    image: jusk2/onem2m-rosemary
    ports:
      - 7599:7599
    restart: always
    depends_on:
      - db
  
  thyme:
    image: jusk2/onem2m-thyme
    ports: 
      - 3105:3105
    restart: always
    depends_on:
      - db

  co2:
    image: jusk2/onem2m-tas-co2
    restart: always
  
  temp:
    image: jusk2/onem2m-tas-temp
    restart: always
