version: "3.3"

services: 
  
  mobius:
    image: jusk2/mobius
    network_mode: host
    ports:
      - 7579:7579
      - 9727:9727
      - 3105:3105
      - 8081:8081
    restart: always
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 10s"
    depends_on:
      - db

  db:
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: "dksdlfduq2"
     MYSQL_DATABASE: "mobiusdb"
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   volumes:
     - ./init/:/docker-entrypoint-initdb.d/
   network_mode: host
   healthcheck:
     test: ["CMD", "mysqladmin", "--password=dksdlfduq2", "ping"]
     interval: 20s
     timeout: 20s 
     retries: 5 
   ports:
     - 3306:3306 

  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    network_mode: host
    ports:
      - 1883:1883
    depends_on:
      - db