version: "3.2"

services: 
  
  # db:
  #   image: jusk2/postgres:13
  #   environment:
  #     - POSTGRES_DB=mobiusdb
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=dksdlfduq2
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./init/:/docker-entrypoint-initdb.d/

  mobius:
    image: jusk2/onem2m-mobius
    ports:
      - 7579:7579
    network_mode: host
    restart: always
    # depends_on:
    #   - db

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    network_mode: host
    # depends_on:
    #   - db

  rosemary:
    image: jusk2/onem2m-rosemary
    ports:
      - 7599:7599
    network_mode: host
    restart: always
    # depends_on:
    #   - db
  
  thyme:
    image: jusk2/onem2m-thyme
    ports: 
      - 3105:3105
    network_mode: host
    restart: always
    # depends_on:
    #   - db

  co2:
    image: jusk2/onem2m-tas-co2
    network_mode: host
    restart: always
  
  temp:
    image: jusk2/onem2m-tas-temp
    network_mode: host
    restart: always
