FROM ubuntu:18.04

LABEL seongwon="seongwon@edu.hanbat.ac.kr"
ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Asia/Seoul

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils build-essential evince
RUN apt-get install -y apt-transport-https ca-certificates curl \
    gnupg-agent software-properties-common wget 

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add
RUN apt-get update && apt-get install -y nodejs yarn

WORKDIR $HOME/Thyme

COPY ./nCube-Thyme-Nodejs $HOME/Thyme
RUN npm install -g --unsafe-perm

EXPOSE 3105

ENTRYPOINT ["node", "thyme"]
# CMD [ "node", "thyme" ]
