version: "3.3"

services:
  db:
    image: jusk2/postgres:13
    hostname: mobius-pgsql
    environment:
      - POSTGRES_DB=mobiusdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dksdlfduq2
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - 5432:5432
